#!/bin/bash

targetDirectory="/path/to/targetdirectory" # Without a slash at the end!

while :
do

  # as this is recursive it is also going to trigger when you copy something in a subdirectory of that path
  pathToFile=`inotifywait -r -q -e close_write --format '%w%f' /path/to/watch` 
  filename=`echo $pathToFile | rev | cut -f 1 -d / | rev`
  
  echo "copying $pathToFile to $targetDirectory/$filename and removing it from source afterwards"  
  cp $pathToFile $targetDirectory/$filename
  rm $pathToFile
  
  echo "Setting up rights for $filename"
  chown mc:mc $targetDirectory/$filename

done
